# Generated by Django 5.2.5 on 2025-10-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(
                choices=[("won", "Korean Won"), ("usd", "US Dollar")],
                default="won",
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("kr", "Korean"), ("en", "English")],
                default="kr",
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        ),
    ]
