# Generated by Django 5.2.5 on 2025-09-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="양수만 입력 가능", verbose_name="가격"
                    ),
                ),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=140)),
                (
                    "pets_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="이 집은 반려동물을 허용합니까?",
                        verbose_name="반려동물 허용?",
                    ),
                ),
            ],
        ),
    ]
