# Generated by Django 5.2.5 on 2025-10-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="description",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="perk",
            name="description",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
