# Generated by Django 5.2.5 on 2025-10-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0002_alter_experience_description_alter_perk_description"),
        ("rooms", "0004_alter_amenity_options"),
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="experiences",
            field=models.ManyToManyField(
                blank=True, null=True, to="experiences.experience"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="rooms",
            field=models.ManyToManyField(blank=True, null=True, to="rooms.room"),
        ),
    ]
