# Generated by Django 5.2.5 on 2025-10-21 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="eexperience_time",
            new_name="experience_time",
        ),
    ]
